### PR TITLE
Added `%a` schema option to filename generation

### LINKED ISSUE #3: %a not supported in annotation format string
### Description

The %a format specifier should be supported in the Annotation Camera Settings, as
in the original raspimjpeg back end module.

### Additional Information (Optional)

This feature originally worked in raspimjpeg by including the contents of this file in the formatted annotation string shown at the top of the camera image.

/dev/shm/mjpeg/user_annotate.txt

### Checks

- [X] I have not found any related feature requests
- [X] I have not found this feature in the application
- [ ] I want to contribute to the development of this feature

### PR DESCRIPTION
**Pull request by kaihokori**
# Description

## Summary of Changes

- Merged changes from PR #2 
- Added the `%a` option for annotations which reads contents from the `/dev/shm/mjpeg/user_annotate.txt` file. 
- Updated the README.md file to reflect the filename schema. 

## Additional Comments

This PR resolves feature request #3

### CODE REVIEW

**Comment by kaihokori** [comment]
Awaiting confirmation that this functionality works (I blindly coded this, lol)

**Comment by hogwell** [comment]
Thanks for this fix!

This code change so far looks like it will work for my particular configuration of:

```
user_annotate /dev/shm/mjpeg/user_annotate.txt
```
in my /etc/raspimjpeg file.

(This is the default value from the Rpi_Cam_Web_Interface install.)

More generally, though, the code should use the 'user_annotate' configuration option to get the right filename.

**Comment by kaihokori** [comment]
Didn't think about that sorry! Would you mind verifying this works?

**Comment by hogwell** [comment]
I can verify that this new code in process.py works now with my changing annotations.
Thanks!

**Pull request merged**
